version: '3.8'

services:
  cringesweeper:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Required: Platform-specific credentials
      # For Bluesky:
      - BLUESKY_USERNAME=${BLUESKY_USERNAME:-}
      - BLUESKY_APP_PASSWORD=${BLUESKY_APP_PASSWORD:-}
      
      # For Mastodon:
      - MASTODON_USERNAME=${MASTODON_USERNAME:-}
      - MASTODON_ACCESS_TOKEN=${MASTODON_ACCESS_TOKEN:-}
      - MASTODON_INSTANCE=${MASTODON_INSTANCE:-}
      
      # Optional: Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
    # Example command with common settings
    # Uncomment and modify as needed
    command: >
      ./cringesweeper server
      --platform=bluesky
      --max-post-age=30d
      --preserve-pinned
      --preserve-selflike
      --prune-interval=1h
      --port=8080
      --log-level=info
    
    # Restart policy for long-running service
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    profiles:
      - monitoring

  # Optional: Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  grafana-storage: