# Prometheus configuration for CringeSweeper monitoring
# This configuration monitors CringeSweeper instances and provides alerting

global:
  scrape_interval: 30s
  evaluation_interval: 30s

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configuration
scrape_configs:
  # CringeSweeper instances
  - job_name: 'cringesweeper'
    static_configs:
      - targets:
        - 'localhost:8080'     # Local development instance
        - 'cringesweeper:8080' # Docker compose service
    scrape_interval: 15s
    metrics_path: /metrics
    honor_labels: true
    
    # Optional: Add labels to identify different environments
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        regex: 'localhost:.*'
        target_label: environment
        replacement: 'development'
      - source_labels: [__address__]
        regex: 'cringesweeper:.*'
        target_label: environment
        replacement: 'production'

  # Multiple CringeSweeper instances (for production deployments)
  - job_name: 'cringesweeper-production'
    static_configs:
      - targets:
        - 'cringesweeper-prod-1:8080'
        - 'cringesweeper-prod-2:8080'
    scrape_interval: 15s
    metrics_path: /metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: environment
        replacement: 'production'

  # Kubernetes deployment (if using Kubernetes)
  - job_name: 'cringesweeper-k8s'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - cringesweeper
    relabel_configs:
      # Only scrape pods with the right annotations
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # Self-monitoring: Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Optional: Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'localhost:9100'
        - 'node-exporter:9100'
    scrape_interval: 30s

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB